CREATE TABLE CUSTOMER (
C_ID varchar(25) PRIMARY KEY,
C_NAME varchar(25),
PH bigint not NULL,
EMAIL varchar(50),
PASSWORD VARCHAR(50)
);


create table c_address (
CADDRESS_ID INT auto_increment primary KEY,
STREET_NAME varchar(50),
CITY varchar(50),
STATE varchar(50),
COUNTRY varchar(30)
);  

ALTER TABLE C_ADDRESS ADD COLUMN C_ID VARCHAR(50);



ALTER TABLE C_ADDRESS ADD CONSTRAINT FK_ADDR_CUS FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID);

ALTER TABLE CUSTOMER MODIFY PASSWORD varchar(100);

ALTER TABLE CUSTOMER ADD CONSTRAINT unique_email UNIQUE (EMAIL);

ALTER TABLE CUSTOMER ADD CONSTRAINT unique_ph UNIQUE (PH);

ALTER TABLE CUSTOMER MODIFY EMAIL VARCHAR(50);


